export const ADD_ARTICLE = "ADD_ARTICLE";
export const RESET_ARTICLES = "RESET_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
